---
- name: Install frontend packages
  npm:
    path: "{{ app_dest }}/frontend"

- name: Create frontend env file
  template:
    src: frontend.env.j2
    dest: "{{ app_dest }}/frontend/.env"

- name: Build frontend
  shell: npm run build
  args:
    chdir: "{{ app_dest }}/frontend"