---
- name: Create frontend env file
  template:
    src: frontend.env.j2
    dest: "{{ app_dest }}/frontend/.env"
    owner: ubuntu
    group: ubuntu
    
- name: Install frontend packages
  npm:
    path: "{{ app_dest }}/frontend"
    state: present
  become: true
  become_user: ubuntu

- name: Build frontend
  shell: npm run build
  args:
    chdir: "{{ app_dest }}/frontend"
    creates: "{{ app_dest }}/frontend/build/index.html"
  become: true
  become_user: ubuntu