---
- name: deploy pm2 file for backend
  template:
    src: pm.config.js.j2
    dest: "{{ app_dir }}/backend/pm.config.js"
    owner: ubuntu
    group: ubuntu

- name: Start/reload Backend
  command: pm2 startOrReload pm.config.js
  args:
    chdir: "{{ app_dir }}/backend"
  become: true
  become_user: ubuntu
  environment: 
    PM2_HOME: "/home/ubuntu/.pm2"

- name: Save PM2 Processes
  shell: pm2 save
  become: true
  become_user: ubuntu
  environment: 
    PM2_HOME: "/home/ubuntu/.pm2"

- name: PM2 systemd service
  command: pm2 startup systemd -u ubuntu --hp /home/ubuntu
  become: true
  register: pm2_startup
  changed_when: "'already' not in pm2_startup.stdout | default('')"