---
- name: Create Mongo Admin User
  shell: |
    mongosh admin --eval '
    db.createUser({
      user:"traveladmin",
      pwd:"Travel@123",
      roles:[{role:"root",db:"admin"}]
    })'
  ignore_errors: yes

- name: Create TravelMemory User
  shell: |
    mongosh travelmemorydb \
    -u traveladmin \
    -p Travel@123 \
    --authenticationDatabase admin \
    --eval '
    db.createUser({
      user:"traveluser",
      pwd:"TravelUser@123",
      roles:[{role:"readWrite",db:"travelmemorydb"}]
    })'
  ignore_errors: yes