app_repo: "https://github.com/UnpredictablePrashant/TravelMemory.git"
app_dir: "/opt/travelmemory"
nodejs_version: 18
app_port: 3001

mongodb_port: 27017
mongo_version: "6.0"
mongo_db_name: "travelmemory"
mongo_app_user: "traveluser"
mongo_admin_password: "{{vault_mongo_admin_password}}"
mongo_app_password: "{{vault_mongo_app_password}}"

my_ip_cidr: "<MY_IP>/32"
vpc_cidr: "10.0.0.0/16"
